FROM alpine:3.12

WORKDIR /tftproot

RUN apk add --no-cache dnsmasq && \
        wget http://boot.ipxe.org/undionly.kpxe && \
        wget http://boot.ipxe.org/ipxe.efi

ENTRYPOINT ["/usr/sbin/dnsmasq"]
